// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPdOrH1h_3a-wQG_8gdhuksTATJ0KQUg0',
    appId: '1:755154744773:web:6f28931cc4679179fac7ac',
    messagingSenderId: '755154744773',
    projectId: 'lostnfound-49c8b',
    authDomain: 'lostnfound-49c8b.firebaseapp.com',
    storageBucket: 'lostnfound-49c8b.appspot.com',
    measurementId: 'G-CQS7SBJEX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOMD8vu5eqGi7n-Vns-BFTk8y-21Wfd8',
    appId: '1:755154744773:android:ae03d5559ec969b8fac7ac',
    messagingSenderId: '755154744773',
    projectId: 'lostnfound-49c8b',
    storageBucket: 'lostnfound-49c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAY7xtcUrBCarOQHGd1U9wxubEndqO3R4',
    appId: '1:755154744773:ios:feb0b2746cfd7635fac7ac',
    messagingSenderId: '755154744773',
    projectId: 'lostnfound-49c8b',
    storageBucket: 'lostnfound-49c8b.appspot.com',
    iosBundleId: 'com.pexalyze.lostnfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAY7xtcUrBCarOQHGd1U9wxubEndqO3R4',
    appId: '1:755154744773:ios:722bf2d35e246ee5fac7ac',
    messagingSenderId: '755154744773',
    projectId: 'lostnfound-49c8b',
    storageBucket: 'lostnfound-49c8b.appspot.com',
    iosBundleId: 'com.pexalyze.lostnfound.RunnerTests',
  );
}
